/**
 * GamutChart — hand-written inline SVG for the two converter pages.
 *
 * No chart library, no canvas, no runtime data fetch: both charts are plain
 * elements in the exported HTML and cost zero kilobytes of JavaScript. Every
 * number arrives as a prop from data/color-stats.json, which is generated by
 * scripts/build-color-stats.mjs — nothing here invents a value.
 *
 * Horizontal bars rather than vertical: category labels stay horizontal, which
 * is the only layout that survives a 360px-wide phone without either rotating
 * text or truncating it.
 *
 * Both charts render a <title> and <desc> inside the SVG for assistive tech,
 * and both pages follow them with a written takeaway — Google reads the
 * paragraph, not the picture.
 */

const AXIS = '#9ca3af';
const GRID = '#f3f4f6';
const LABEL = '#4b5563';
const VALUE = '#111827';

/**
 * DistributionChart — one horizontal bar per bucket of a histogram.
 *
 * @param {object} props
 * @param {string} props.id
 * @param {string} props.title       SVG <title>: the chart's accessible name.
 * @param {string} props.desc        SVG <desc>: what the shape of the data is.
 * @param {Array<{ label: string, count: number, pct: number }>} props.buckets
 * @param {string} props.unitLabel   What one bar counts, e.g. "PMS numbers".
 * @param {string} [props.barColor]
 * @param {string} [props.highlightColor]  Fill for the tallest bar.
 */
export function DistributionChart({
  id,
  title,
  desc,
  buckets,
  unitLabel,
  barColor = '#c44eed',
  highlightColor = '#7e22ce',
}) {
  const ROW = 40;
  const TOP = 14;
  const BOTTOM = 34;
  const LABEL_W = 132;
  const VALUE_W = 92;
  const W = 480;
  const H = TOP + buckets.length * ROW + BOTTOM;
  const plotX = LABEL_W;
  const plotW = W - LABEL_W - VALUE_W;

  const max = Math.max(...buckets.map((b) => b.count), 1);
  // Round the axis up to a clean number so the gridlines mean something.
  const step = 10 ** Math.floor(Math.log10(max));
  const axisMax = Math.ceil(max / step) * step;
  const ticks = [0, axisMax / 2, axisMax];

  const titleId = `${id}-title`;
  const descId = `${id}-desc`;

  return (
    <svg
      viewBox={`0 0 ${W} ${H}`}
      preserveAspectRatio="xMidYMid meet"
      role="img"
      aria-labelledby={`${titleId} ${descId}`}
      style={{ width: '100%', height: 'auto', display: 'block' }}
    >
      <title id={titleId}>{title}</title>
      <desc id={descId}>{desc}</desc>

      {ticks.map((t) => {
        const x = plotX + (t / axisMax) * plotW;
        return (
          <g key={t}>
            <line x1={x} y1={TOP} x2={x} y2={TOP + buckets.length * ROW} stroke={GRID} strokeWidth="1" />
            <text x={x} y={H - 12} textAnchor="middle" fontSize="12" fill={AXIS}>
              {t}
            </text>
          </g>
        );
      })}
      <text x={plotX + plotW / 2} y={H - 1} textAnchor="middle" fontSize="11" fill={AXIS}>
        {unitLabel}
      </text>

      {buckets.map((b, i) => {
        const y = TOP + i * ROW;
        const barH = 22;
        const barW = Math.max((b.count / axisMax) * plotW, b.count > 0 ? 2 : 0);
        const isMax = b.count === max;
        return (
          <g key={b.label}>
            <text x={LABEL_W - 12} y={y + barH - 5} textAnchor="end" fontSize="14" fill={LABEL} fontWeight="600">
              {b.label}
            </text>
            <rect
              x={plotX}
              y={y}
              width={barW}
              height={barH}
              rx="3"
              fill={isMax ? highlightColor : barColor}
            />
            <text x={plotX + barW + 8} y={y + barH - 5} fontSize="13" fill={VALUE} fontWeight="700">
              {b.count}
              <tspan fill={AXIS} fontWeight="500"> ({b.pct}%)</tspan>
            </text>
          </g>
        );
      })}

      <line
        x1={plotX}
        y1={TOP}
        x2={plotX}
        y2={TOP + buckets.length * ROW}
        stroke={AXIS}
        strokeWidth="1"
      />
    </svg>
  );
}

const INK_COLORS = {
  c: { fill: '#06b6d4', label: 'Cyan' },
  m: { fill: '#ec4899', label: 'Magenta' },
  y: { fill: '#eab308', label: 'Yellow' },
  k: { fill: '#374151', label: 'Black' },
};

/**
 * InkBuildChart — one stacked horizontal bar per colour, showing how its
 * four-colour build divides between C, M, Y and K, with the total ink
 * coverage printed at the end of the bar.
 *
 * @param {object} props
 * @param {string} props.id
 * @param {string} props.title
 * @param {string} props.desc
 * @param {Array<{ code: string, hex: string, cmyk: object, tac: number }>} props.colors
 */
export function InkBuildChart({ id, title, desc, colors }) {
  const ROW = 38;
  const TOP = 40;
  const BOTTOM = 30;
  const LABEL_W = 150;
  const VALUE_W = 60;
  const W = 480;
  const H = TOP + colors.length * ROW + BOTTOM;
  const plotX = LABEL_W;
  const plotW = W - LABEL_W - VALUE_W;

  // A shared scale, so bar length reads directly as total ink laid down.
  const axisMax = 250;
  const titleId = `${id}-title`;
  const descId = `${id}-desc`;
  const channels = ['c', 'm', 'y', 'k'];

  return (
    <svg
      viewBox={`0 0 ${W} ${H}`}
      preserveAspectRatio="xMidYMid meet"
      role="img"
      aria-labelledby={`${titleId} ${descId}`}
      style={{ width: '100%', height: 'auto', display: 'block' }}
    >
      <title id={titleId}>{title}</title>
      <desc id={descId}>{desc}</desc>

      {/* Legend */}
      {channels.map((ch, i) => (
        <g key={ch} transform={`translate(${plotX + i * 78}, 8)`}>
          <rect width="11" height="11" rx="2" fill={INK_COLORS[ch].fill} />
          <text x="16" y="10" fontSize="12" fill={LABEL}>{INK_COLORS[ch].label}</text>
        </g>
      ))}

      {[0, 50, 100, 150, 200, 250].map((t) => {
        const x = plotX + (t / axisMax) * plotW;
        return (
          <g key={t}>
            <line x1={x} y1={TOP - 6} x2={x} y2={TOP + colors.length * ROW} stroke={GRID} strokeWidth="1" />
            <text x={x} y={H - 14} textAnchor="middle" fontSize="11" fill={AXIS}>{t}</text>
          </g>
        );
      })}
      <text x={plotX + plotW / 2} y={H - 2} textAnchor="middle" fontSize="11" fill={AXIS}>
        Total ink coverage (%)
      </text>

      {colors.map((col, i) => {
        const y = TOP + i * ROW;
        const barH = 20;
        let x = plotX;
        return (
          <g key={col.code}>
            <rect
              x={10}
              y={y + 3}
              width="14"
              height="14"
              rx="3"
              fill={col.hex}
              stroke="rgba(0,0,0,0.15)"
            />
            <text x={30} y={y + barH - 5} fontSize="13" fill={LABEL} fontWeight="600">
              {col.code.replace(/^PMS /, '')}
            </text>
            {channels.map((ch) => {
              const v = col.cmyk[ch];
              const w = (v / axisMax) * plotW;
              const seg = (
                <rect
                  key={ch}
                  x={x}
                  y={y}
                  width={w}
                  height={barH}
                  fill={INK_COLORS[ch].fill}
                />
              );
              x += w;
              return v > 0 ? seg : null;
            })}
            <text x={x + 8} y={y + barH - 5} fontSize="12" fill={VALUE} fontWeight="700">
              {col.tac}%
            </text>
          </g>
        );
      })}

      <line x1={plotX} y1={TOP - 6} x2={plotX} y2={TOP + colors.length * ROW} stroke={AXIS} strokeWidth="1" />
    </svg>
  );
}

/**
 * ChartFigure — the wrapper both charts sit in: a <figure> with a visible
 * caption and, below it, the written takeaway that carries the point in text.
 */
export function ChartFigure({ caption, children, takeaway }) {
  return (
    <>
      <figure style={{ margin: '0 0 1rem', padding: 0 }}>
        <div
          style={{
            border: '1px solid #f3f4f6',
            borderRadius: '0.875rem',
            background: '#fff',
            padding: '1rem 0.75rem 0.5rem',
          }}
        >
          {children}
        </div>
        <figcaption
          style={{
            fontSize: '0.76rem',
            color: '#6b7280',
            lineHeight: 1.6,
            marginTop: '0.6rem',
            fontStyle: 'italic',
          }}
        >
          {caption}
        </figcaption>
      </figure>
      {takeaway}
    </>
  );
}
