import { Html, Head, Main, NextScript } from 'next/document';

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        {/* Self-hosted Plus Jakarta Sans — @font-face lives in styles/globals.css.
            Preloading the latin subset starts the download in the same round trip
            as the HTML, instead of waiting for the stylesheet to be parsed first. */}
        <link
          rel="preload"
          href="/fonts/plus-jakarta-sans-latin.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        {/* 'Plus Jakarta Fallback' is Arial re-scaled to Plus Jakarta Sans' real
            metrics (xWidthAvg 468/1000 vs Arial's 913/2048), so text laid out
            in the fallback occupies the same box as the webfont and swapping
            causes no shift. Declared inline rather than in globals.css because
            it only helps if the browser sees it before first paint; local()
            sources mean it costs no request. */}
        <style
          dangerouslySetInnerHTML={{
            __html:
              "@font-face{font-family:'Plus Jakarta Fallback';" +
              "src:local('Arial'),local('Helvetica Neue'),local('Liberation Sans');" +
              'size-adjust:104.98%;ascent-override:98.88%;descent-override:21.15%;line-gap-override:0%}',
          }}
        />

        {/* Icons — generated by scripts/generate-icons.mjs */}
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <meta name="theme-color" content="#c44eed" />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
