import { ArrowRightLeft } from 'lucide-react';
import PantoneToXPage from '../components/PantoneToXPage';
import ConversionChartTable from '../components/ConversionChartTable';
import { DistributionChart, InkBuildChart, ChartFigure } from '../components/GamutChart';
import FAQSection from '../components/FAQSection';
import { Section, P, H3, Steps, Bullets, Callout, A, RelatedLinks } from '../components/LongFormSection';
import stats from '../data/color-stats.json';

const CANONICAL = 'https://pantoneconverter.com/pantone-to-cmyk/';
const ACCENT = '#ea580c';

// Values come from data/color-stats.json, generated by
// scripts/build-color-stats.mjs out of data/pantone.json. Nothing here is typed
// in by hand — including the caveats, which are keyed off the script's own
// cmykIsDerived check.
const C = Object.fromEntries(stats.chart.map((row) => [row.code, row]));
const build = (code) => {
  const { c, m, y, k } = C[code].cmyk;
  return `C ${c} M ${m} Y ${y} K ${k}`;
};
const { tacHistogram, hardestForProcess, inkBuild, counts, noHeadroomCount } = stats;

const mono = { fontFamily: 'monospace', fontWeight: 700 };

// ─── The chart table ─────────────────────────────────────────────────────────

const CHART_COLUMNS = [
  { key: 'name', label: 'Pantone colour' },
  { key: 'c', label: 'C %', align: 'right' },
  { key: 'm', label: 'M %', align: 'right' },
  { key: 'y', label: 'Y %', align: 'right' },
  { key: 'k', label: 'K %', align: 'right' },
  { key: 'tac', label: 'TAC', align: 'right', hint: 'Total area coverage: C + M + Y + K' },
  { key: 'flag', label: 'Ink headroom' },
];

const inkCell = (value, color) => (
  <span style={{ fontVariantNumeric: 'tabular-nums', color: value === 0 ? '#d1d5db' : color, fontWeight: value >= 95 ? 800 : 600 }}>
    {value}
  </span>
);

/** The honest flag: how hard the build leans on a chromatic ink. */
function headroomFlag(row) {
  if (row.heavy > 0) {
    return (
      <span style={{ color: '#b91c1c', fontWeight: 700, fontSize: '0.74rem' }}>
        None — {row.maxInk}% ink
      </span>
    );
  }
  if (row.maxInk >= 80) {
    return <span style={{ color: '#9a3412', fontWeight: 700, fontSize: '0.74rem' }}>Tight — {row.maxInk}%</span>;
  }
  return <span style={{ color: '#6b7280', fontSize: '0.74rem' }}>Comfortable</span>;
}

const CHART_ROWS = stats.chart.map((row) => ({
  id: row.name,
  hex: row.hex,
  search: `${row.code} ${row.name} ${row.hex} ${row.family} ${row.cmyk.c} ${row.cmyk.m} ${row.cmyk.y} ${row.cmyk.k}`.toLowerCase(),
  cells: [
    <span key="n">
      {row.code}
      {row.collection !== 'coated' && (
        <span style={{ color: '#6b7280', fontWeight: 500, fontSize: '0.7rem', marginLeft: '0.35rem' }}>
          ({row.collection === 'metallic' ? 'metallic' : 'neon'})
        </span>
      )}
    </span>,
    inkCell(row.cmyk.c, '#0e7490'),
    inkCell(row.cmyk.m, '#be185d'),
    inkCell(row.cmyk.y, '#a16207'),
    inkCell(row.cmyk.k, '#374151'),
    <strong key="t" style={{ color: '#111827', fontVariantNumeric: 'tabular-nums' }}>{row.tac}%</strong>,
    headroomFlag(row),
  ],
}));

// ─── Hardest-for-process table ───────────────────────────────────────────────

function NoHeadroomTable() {
  const cell = {
    padding: '0.5rem 0.7rem', borderBottom: '1px solid #f3f4f6',
    fontSize: '0.79rem', color: '#374151', whiteSpace: 'nowrap',
  };
  const th = {
    ...cell, background: '#f9fafb', fontWeight: 800, fontSize: '0.7rem',
    color: '#4b5563', textTransform: 'uppercase', letterSpacing: '0.05em',
    borderBottom: '1.5px solid #e5e7eb', textAlign: 'left',
  };
  return (
    <div style={{ overflowX: 'auto', border: '1px solid #f3f4f6', borderRadius: '0.875rem', background: '#fff' }}>
      <table style={{ borderCollapse: 'collapse', width: '100%', minWidth: '38rem' }}>
        <caption style={{ captionSide: 'top', textAlign: 'left', padding: '0.8rem 0.7rem', fontSize: '0.76rem', color: '#4b5563', lineHeight: 1.6 }}>
          The 25 coated PMS colours whose process build leans hardest on the chromatic inks, ranked by
          how many of cyan, magenta and yellow the recipe drives to 95% or more, then by total ink
          coverage. These are the builds with nowhere left to go on press.
        </caption>
        <thead>
          <tr>
            <th scope="col" style={th}>PMS colour</th>
            <th scope="col" style={th}>Spot HEX</th>
            <th scope="col" style={th}>Process build</th>
            <th scope="col" style={{ ...th, textAlign: 'right' }}>TAC</th>
            <th scope="col" style={{ ...th, textAlign: 'right' }}>Inks at 95%+</th>
          </tr>
        </thead>
        <tbody>
          {hardestForProcess.map((row) => (
            <tr key={row.name}>
              <th scope="row" style={{ ...cell, fontWeight: 700, color: '#111827', textAlign: 'left' }}>
                <span aria-hidden="true" style={{ display: 'inline-block', width: '0.7rem', height: '0.7rem', borderRadius: '2px', background: row.hex, border: '1px solid rgba(0,0,0,0.15)', marginRight: '0.45rem' }} />
                {row.code}
              </th>
              <td style={cell}><code style={mono}>{row.hex}</code></td>
              <td style={cell}>C {row.cmyk.c} · M {row.cmyk.m} · Y {row.cmyk.y} · K {row.cmyk.k}</td>
              <td style={{ ...cell, textAlign: 'right', fontWeight: 700 }}>{row.tac}%</td>
              <td style={{ ...cell, textAlign: 'right', fontWeight: 700, color: row.heavy > 1 ? '#b91c1c' : '#9a3412' }}>{row.heavy}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

// ─── Coated / uncoated build comparison ──────────────────────────────────────

const CU_BUILDS = ['PMS 186 C', 'PMS 485 C', 'PMS Reflex Blue C', 'PMS 300 C', 'PMS 355 C', 'PMS Black C'];

// ─── How-to procedures ───────────────────────────────────────────────────────

const HOW_TO = [
  {
    id: 'illustrator-cmyk',
    app: 'Adobe Illustrator',
    heading: 'Converting Pantone swatches to CMYK in Illustrator',
    intro: 'Illustrator will convert one swatch, a selection, or the whole document, and the three routes behave differently enough to matter.',
    steps: [
      'To convert one swatch permanently: double-click it in the Swatches panel, change Color Type from Spot Color to Process Color, set Color Mode to CMYK, and click OK. Everything using that swatch updates.',
      'To convert a selection only: select the objects, then choose Edit, then Edit Colors, then Convert to CMYK. This rewrites the fills in place and leaves the spot swatch in the panel.',
      'To convert everything at output: choose Window, then Output, then Separations Preview, tick Overprint Preview, and check which plates are still listed. Any spot plate you did not intend shows up here.',
      'Load the right book before you start. Choose Window, then Swatch Libraries, then Color Books, then PANTONE+ Solid Coated for a C number or PANTONE+ Solid Uncoated for a U number — Illustrator derives the process build from whichever book the swatch came from.',
      'Set the document CMYK profile deliberately under Edit, then Assign Profile. A build converted against U.S. Web Coated (SWOP) is not the same build as one converted against Coated FOGRA39.',
    ],
  },
  {
    id: 'indesign-cmyk',
    app: 'Adobe InDesign',
    heading: 'Converting Pantone to CMYK in InDesign with the Ink Manager',
    intro: 'InDesign has the better tool for this, because the Ink Manager converts at export without touching your swatches — so the file stays correct if the job goes back to spot.',
    steps: [
      'Open Window, then Output, then Ink Manager. Every ink the document will separate onto its own plate is listed here, including spot inks arriving inside placed EPS and PDF artwork.',
      'Tick “All Spots to Process” at the bottom of the dialog. The spot plates disappear from the list and the colours will output as process builds.',
      'Leave the swatches themselves alone. Because the change lives in the Ink Manager rather than in the swatch definitions, you can untick it later and the spot colours come back intact.',
      'Use the alias column instead when two spot swatches are really the same ink — for example a supplied logo carrying “PANTONE 186 C” and your own “Brand Red”. Aliasing them merges the plates and saves a plate charge.',
      'Check the result in Window, then Output, then Separations Preview before you export, and again in the exported PDF, since placed artwork can reintroduce a spot plate.',
    ],
  },
];

// ─── FAQ ─────────────────────────────────────────────────────────────────────

const FAQ = [
  {
    question: 'What is Pantone 485 C in CMYK?',
    answer: `The converter on this page returns ${build('PMS 485 C')} for Pantone 485 C, a total ink coverage of ${C['PMS 485 C'].tac}%. That is a starting build, not a guaranteed match: 485 is one of the reds that four-colour process struggles to hold, and a press proof will read duller than the spot ink. If the red is load-bearing for the brand, run it as a fifth spot plate.`,
  },
  {
    question: 'What is the CMYK value of Pantone Black C?',
    answer: `Pantone Black C converts to ${build('PMS Black C')} — note the magenta and yellow. Black C is a warm black, not a neutral one, so a build of 100% K alone prints noticeably cooler and flatter than the spot ink. The magenta and yellow are what carry the warmth, and the 82% K rather than 100% is what keeps it from going dead.`,
  },
  {
    question: 'How do I convert PMS to CMYK?',
    answer: 'Search the PMS number in the tool at the top of this page and the four ink percentages appear immediately. Inside Adobe software, change the swatch from Spot Color to Process Color in Illustrator, or tick “All Spots to Process” in the InDesign Ink Manager. Whichever route you take, tell your printer which CMYK profile the build was made against, because the same PMS number produces different percentages under SWOP, GRACoL and FOGRA.',
  },
  {
    question: 'Why does my Pantone color shift when converted to CMYK?',
    answer: 'Because a spot ink is one pre-mixed pigment laid down as a solid film, and a process build is a halftone pattern of up to four transparent inks that your eye mixes. The four process inks describe a smaller range of colours than the spot ink library does, so any spot colour outside that range gets pulled to the nearest reachable one. Saturated oranges, blues, greens and violets shift the most.',
  },
  {
    question: 'What is Pantone 871 C in CMYK?',
    answer: `Pantone 871 C is the standard metallic gold, and this converter returns ${build('PMS 871 C')} for it. That build reproduces the flat olive-brown a gold ink looks like when you photograph it, and none of the metallic reflection, because process inks contain no metal flake. If the job needs gold, it needs either a metallic spot plate or a foil.`,
  },
  {
    question: 'Should I convert Pantone to CMYK before sending to print?',
    answer: 'Ask the printer first. If the job runs four-colour process, converting yourself lets you see and approve the shift rather than discovering it on a proof. If the job runs spot, or spot plus process, converting destroys the specification and costs you the accuracy you were paying for. Never convert a file without knowing which of the two you are printing.',
  },
  {
    question: 'What is the CMYK for Pantone Reflex Blue?',
    answer: `This converter returns ${build('PMS Reflex Blue C')} for Pantone Reflex Blue C, which is a total ink coverage of ${C['PMS Reflex Blue C'].tac}% — one of the heaviest in the deck. Cyan is at 100%, so the build has no headroom left; anything the recipe still needs has to come from black, which is why the process version reads darker and greyer than the spot ink.`,
  },
  {
    question: 'Is CMYK conversion the same for coated and uncoated?',
    answer: 'No. The C and U variants of a PMS number are different published colours, so they produce different builds. Beyond that, uncoated stock absorbs more ink and gains more dot, so a press running uncoated is normally profiled with a lower total ink limit and different tone curves — the same numbers behave differently on the sheet.',
  },
  {
    question: 'What is Total Area Coverage and why does it matter?',
    answer: `TAC is simply C plus M plus Y plus K for a given build. It matters because ink has to dry: too much of it on one spot and the sheet offsets onto the next one, refuses to dry between passes, or cracks at the fold. Commercial sheetfed work is usually limited to about 300%, coldset web newsprint to around 240%. The builds in the chart on this page top out at ${tacHistogram.max}%, so they leave room for the extra black a rich-black background adds underneath.`,
  },
  {
    question: 'Why is Pantone Process Black C not just 100% K?',
    answer: 'Process Black is the K ink itself — the black already on the press for four-colour work — so as a specification it means 100% K by definition. Pantone Black C is a different thing: a separate warm spot black from the solid deck with its own pigment, which is why it converts to a build that includes magenta and yellow rather than to plain K.',
  },
  {
    question: 'Which Pantone colours cannot be printed in CMYK at all?',
    answer: 'The metallics and the fluorescents, without qualification: process inks contain no metal flake and do not fluoresce, so nothing four-colour does can imitate them. Beyond those, the saturated inks lose the most — Orange 021, Red 032, Reflex Blue, Blue 072, the 265 and 266 violets and the 354 and 355 greens all read visibly duller as process builds. These are candidates for a fifth plate rather than a conversion.',
  },
  {
    question: 'Do I need a fifth plate, or will the CMYK build do?',
    answer: 'It comes down to how much of the sheet the colour occupies and how well the audience knows it. A logo the size of a stamp on a leaflet is fine as a process build. A colour that fills a whole cover, or one customers recognise from a distance, is worth the plate. So is any colour our chart flags as having no ink headroom, because those are the ones a press cannot chase.',
  },
  {
    question: 'What is a rich black and when should I use one?',
    answer: 'A rich black is 100% K with cyan, magenta or yellow underneath it, used because 100% K alone looks washed-out over a large area. A common recipe is 60C 40M 40Y 100K, giving 240% coverage. Use it for large solid areas and never for small text, where the plates cannot stay in register and the type ends up fringed with colour.',
  },
  {
    question: 'Are these CMYK values measured on a press?',
    answer: 'No, and no honest converter can claim otherwise without an ICC characterisation of a specific press condition. The builds here are computed from each colour’s published sRGB value by the standard non-colour-managed formula, which is what makes them reproducible and a reasonable starting point. Treat them as a first build to proof and correct, not as a final press-ready specification.',
  },
];

// ─── Structured data ─────────────────────────────────────────────────────────

const PUBLISHED = '2024-11-18';
const MODIFIED = stats.generatedAt;

const faqSchema = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: FAQ.map((item) => ({
    '@type': 'Question',
    name: item.question,
    acceptedAnswer: { '@type': 'Answer', text: item.answer },
  })),
};

const howToSchema = {
  '@context': 'https://schema.org',
  '@type': 'HowTo',
  name: 'How to convert Pantone spot colours to CMYK for print',
  description:
    'Convert Pantone PMS spot colours into four-colour process builds in Adobe Illustrator and Adobe InDesign, including the Ink Manager route that converts at output without altering swatches.',
  totalTime: 'PT5M',
  dateModified: MODIFIED,
  tool: HOW_TO.map((section) => ({ '@type': 'HowToTool', name: section.app })),
  step: HOW_TO.map((section) => ({
    '@type': 'HowToSection',
    name: section.heading,
    itemListElement: section.steps.map((text, i) => ({
      '@type': 'HowToStep',
      position: i + 1,
      name: `${section.app} step ${i + 1}`,
      text,
      url: `${CANONICAL}#${section.id}`,
    })),
  })),
};

const datasetSchema = {
  '@context': 'https://schema.org',
  '@type': 'Dataset',
  name: 'Pantone to CMYK ink chart — 100 most-used PMS colours',
  description:
    'Four-colour process breakdowns for 100 Pantone PMS colours, with cyan, magenta, yellow and black percentages, total area coverage, and an ink-headroom flag marking builds that drive a chromatic ink to 95% or more.',
  url: `${CANONICAL}#cmyk-chart`,
  license: 'https://creativecommons.org/licenses/by/4.0/',
  isAccessibleForFree: true,
  datePublished: PUBLISHED,
  dateModified: MODIFIED,
  creator: { '@type': 'Organization', name: 'PantoneConverter.com', url: 'https://pantoneconverter.com/' },
  variableMeasured: [
    { '@type': 'PropertyValue', name: 'Cyan', unitText: 'PERCENT' },
    { '@type': 'PropertyValue', name: 'Magenta', unitText: 'PERCENT' },
    { '@type': 'PropertyValue', name: 'Yellow', unitText: 'PERCENT' },
    { '@type': 'PropertyValue', name: 'Black', unitText: 'PERCENT' },
    { '@type': 'PropertyValue', name: 'Total area coverage', description: 'C + M + Y + K for the build', unitText: 'PERCENT' },
    { '@type': 'PropertyValue', name: 'Ink headroom', description: 'Count of cyan, magenta and yellow driven to 95% or more' },
  ],
};

// ─── Page ────────────────────────────────────────────────────────────────────

export default function PantoneToCmyk() {
  return (
    <PantoneToXPage
      primaryOutput="cmyk"
      icon={<ArrowRightLeft size={20} color={ACCENT} />}
      iconBg="#fff7ed"
      pageTitle="Pantone to CMYK Converter + Free PMS Ink Chart"
      h1="Pantone to CMYK Converter"
      metaDescription="Free instant Pantone to CMYK converter for 3,231 PMS colours, coated and uncoated, plus a 100-colour ink chart with C M Y K percentages and total coverage."
      canonical={CANONICAL}
      datePublished={PUBLISHED}
      dateModified={MODIFIED}
      toolLabel="Search any PMS colour to get its CMYK build"
      toolHint="Try “485-C”, “Reflex Blue”, “871-C”, “Black-C”, “Cool Gray 11-C”"
      popularHeading="Most-requested process builds — click for the C M Y K values"
      popularNames={[
        'Pantone 485-C', 'Pantone ORANGE-021-C', 'Pantone RED-032-C', 'Pantone RUBINE-RED-C',
        'Pantone REFLEX-BLUE-C', 'Pantone PROCESS-BLUE-C', 'Pantone 355-C', 'Pantone 266-C',
        'Pantone 871-C', 'Pantone 8003-C Metallic', 'Pantone BLACK-C', 'Pantone COOL-GRAY-7-C',
      ]}
      schemas={[faqSchema, howToSchema, datasetSchema]}
      intro={
        <>
          <p style={{ margin: '0 0 0.6rem' }}>
            Converting Pantone to CMYK turns a single pre-mixed spot ink into a four-colour process
            build — Pantone 485 C, for example, comes out as {build('PMS 485 C')}. Search any of the{' '}
            {counts.total.toLocaleString('en-GB')} PMS colours below to get its cyan, magenta, yellow and
            black percentages.
          </p>
          <p style={{ margin: 0 }}>
            Below the tool: a 100-colour PMS to CMYK ink chart with total area coverage and an ink-headroom
            flag, the 25 builds that lean hardest on the press, what rich black and the 300% ink limit
            actually mean for your file, how to convert in Illustrator and the InDesign Ink Manager, and
            when paying for a fifth plate is the cheaper decision.
          </p>
        </>
      }
    >
      {/* ── 3. Conversion chart ───────────────────────────────────────────── */}
      <Section id="cmyk-chart-section" accent={ACCENT} kicker="Ink chart"
        heading="Pantone to CMYK Conversion Chart — 100 Most-Used PMS Colors">
        <P>
          A hundred PMS colours with their four-colour builds: the fourteen base inks the Pantone system
          mixes from, the deck blacks, the Cool Grays, four speciality colours and sixty-four numbered
          colours that recur in brand work. It is a hand-picked set, not a popularity ranking, grouped by
          ink family.
        </P>
        <P>
          <strong>TAC</strong> is total area coverage — the four percentages added together. It is the
          number a prepress operator looks at first, because it decides whether the sheet will dry, and
          whether a rich black underneath will push the total past what the press allows. Across the whole
          coated deck the median build lands at {tacHistogram.median}% and the heaviest,{' '}
          {tacHistogram.heaviest[0].code}, reaches {tacHistogram.heaviest[0].tac}%.
        </P>
        <P>
          <strong>Ink headroom</strong> flags how hard the recipe leans on the chromatic inks. A build
          marked “None” drives cyan, magenta or yellow to 95% or more, which means the press has nothing
          left to give: if the printed sheet comes back short of the target, there is no ink adjustment
          that fixes it. {noHeadroomCount} of the {counts.coated.toLocaleString('en-GB')} coated colours
          fall into that category. This is a property of the recipe, computed exactly — it is not a
          measured press ΔE, and the{' '}
          <a href="#methodology" style={{ color: '#7c3aed', fontWeight: 600 }}>methodology note</a>{' '}
          explains why we do not publish one.
        </P>
        <ConversionChartTable
          id="cmyk-chart"
          caption="Pantone PMS to CMYK ink chart. Percentages are the process build this site's converter returns for each colour; TAC is their sum; ink headroom counts how many of cyan, magenta and yellow the build drives to 95% or more. Scroll sideways on a narrow screen; the colour name column stays in place."
          columns={CHART_COLUMNS}
          rows={CHART_ROWS}
          initialVisible={25}
          revealLabel="Show all 100 builds"
          filterPlaceholder="Filter by PMS number or ink percentage…"
          footnote="Metallic and neon rows are marked. Four-colour process cannot reproduce either — see “Which Pantone colours cannot be reproduced in CMYK” below."
        />
      </Section>

      {/* ── 4. Coated vs uncoated builds ──────────────────────────────────── */}
      <Section id="coated-uncoated-builds" accent={ACCENT} kicker="C vs U"
        heading="Coated vs Uncoated CMYK Breakdowns">
        <P>
          The C and U suffixes are not a labelling convention — they are two different published colours,
          so they convert to two different builds. Pantone 186 C and Pantone 186 U are the same ink on
          two papers, and the uncoated printing is lighter and duller because the fibre drinks the
          vehicle and scatters the light. Ask any converter for “186” without a suffix and you are
          letting it choose for you.
        </P>
        <div style={{ overflowX: 'auto', border: '1px solid #f3f4f6', borderRadius: '0.875rem', background: '#fff', marginBottom: '0.9rem' }}>
          <table style={{ borderCollapse: 'collapse', width: '100%', minWidth: '34rem' }}>
            <caption style={{ captionSide: 'top', textAlign: 'left', padding: '0.8rem 0.7rem', fontSize: '0.76rem', color: '#4b5563', lineHeight: 1.6 }}>
              Six well-known PMS numbers, showing the process build and total ink coverage for the coated
              printing alongside the difference between the coated and uncoated swatches.
            </caption>
            <thead>
              <tr>
                {['PMS colour', 'Coated build', 'TAC', 'C vs U difference'].map((h, i) => (
                  <th key={h} scope="col" style={{
                    padding: '0.5rem 0.7rem', background: '#f9fafb', fontWeight: 800, fontSize: '0.7rem',
                    color: '#4b5563', textTransform: 'uppercase', letterSpacing: '0.05em',
                    borderBottom: '1.5px solid #e5e7eb', textAlign: i === 2 ? 'right' : 'left', whiteSpace: 'nowrap',
                  }}>{h}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {CU_BUILDS.map((code) => {
                const row = C[code];
                const pair = stats.coatedUncoated.find((p) => p.code === code.replace(/ C$/, ''));
                const cell = { padding: '0.5rem 0.7rem', borderBottom: '1px solid #f3f4f6', fontSize: '0.79rem', color: '#374151', whiteSpace: 'nowrap' };
                return (
                  <tr key={code}>
                    <th scope="row" style={{ ...cell, fontWeight: 700, color: '#111827', textAlign: 'left' }}>
                      <span aria-hidden="true" style={{ display: 'inline-block', width: '0.7rem', height: '0.7rem', borderRadius: '2px', background: row.hex, border: '1px solid rgba(0,0,0,0.15)', marginRight: '0.45rem' }} />
                      {row.code}
                    </th>
                    <td style={cell}>{build(code)}</td>
                    <td style={{ ...cell, textAlign: 'right', fontWeight: 700 }}>{row.tac}%</td>
                    <td style={cell}>
                      {pair ? <>ΔE {pair.deltaE.toFixed(2)} <span style={{ color: '#6b7280' }}>— {pair.note.toLowerCase()}</span></> : '—'}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
        <H3>Why uncoated needs different ink percentages</H3>
        <P>
          The reason is dot gain. A halftone dot printed on uncoated stock spreads as the ink wicks into
          the fibres, so a 50% tint on the plate can measure 70% or more on the sheet. Coated stock holds
          the dot much closer to its intended size. That is why press profiles for uncoated work carry a
          different tone curve and a lower total ink limit — a build that was engineered against a coated
          profile prints darker, muddier and flatter on uncoated paper if nobody re-separates it.
        </P>
        <P>
          Two practical consequences. First, convert the variant your brand sheet names rather than the
          bare number. Second, if the same brand colour is going onto both coated and uncoated stock in
          the same campaign, expect two different builds and say so in the guidelines — chasing one build
          across both papers is how colour arguments start. The{' '}
          <A href="/learn/coated-vs-uncoated/">coated vs uncoated guide</A> covers the paper side in more
          depth, and <A href="/pantone-to-hex/">the Pantone to HEX converter</A> shows the same split on
          the screen side.
        </P>
      </Section>

      {/* ── 5. Cannot be reproduced ───────────────────────────────────────── */}
      <Section id="out-of-gamut" accent={ACCENT} kicker="Gamut"
        heading="Which Pantone Colors Cannot Be Reproduced in CMYK">
        <P>
          Four-colour process describes a smaller set of colours than the Pantone library does. That is
          not a defect in anyone’s software; it is arithmetic. A spot colour is one pre-mixed pigment
          laid down as a solid film at full strength, and the ink maker can reach for whatever pigment
          the colour needs. A process build has four transparent inks and a halftone screen, and every
          colour it can produce lies inside the volume those four inks can mix. Anything outside that
          volume gets pulled to the nearest point on its surface.
        </P>
        <H3>The colours that never survive</H3>
        <Bullets
          items={[
            <>
              <strong>Metallics.</strong> Pantone 871 C, 872 C, 877 C and the whole 8000 series work by
              suspending aluminium or bronze flake, which reflects light directionally so the colour
              shifts as the sheet moves. Process inks contain no metal. Pantone 877 C converts to{' '}
              {build('PMS 877 C')} — a flat grey with no reflection in it at all.
            </>,
            <>
              <strong>Fluorescents.</strong> The 800-series neons re-emit ultraviolet as visible light,
              so they are literally brighter than the white paper around them. No combination of four
              subtractive inks can be brighter than the substrate.
            </>,
            <>
              <strong>The saturated corners.</strong> Orange 021, Red 032, Reflex Blue, Blue 072, the 265
              and 266 violets and the 354 and 355 greens all sit outside or right on the edge of what
              process can reach. They do not disappear — they arrive duller and slightly shifted in hue,
              which is worse, because it looks like a printing mistake rather than an obvious limitation.
            </>,
          ]}
        />
        <H3>Ranking the difficult builds</H3>
        <P>
          The table below ranks the coated deck by <strong>ink headroom</strong>: how many of cyan,
          magenta and yellow the build drives to 95% or more, then by total ink coverage. It is exact
          arithmetic on the published recipe. A build with an ink at 100% is a build the press cannot
          push any further, so if the printed sheet comes back short of target, the only remaining lever
          is black — which darkens the colour rather than saturating it.
        </P>
        <P>
          Deep blues dominate the top of this list, and that is genuinely informative rather than an
          artefact. Colours like Reflex Blue and the 2740s need cyan at 100%, heavy magenta and 45–60%
          black simultaneously: the recipe is asking for a chroma the inks cannot deliver, and the black
          is doing the work that saturation should. That is precisely why those colours print as flat,
          slightly grey navies in process and look electric as spot inks.
        </P>
        <Callout tone="warn" title="What this ranking is and is not">
          It measures the recipe, not a printed sheet. A true out-of-gamut figure needs a
          spectrophotometer reading of the spot ink and an ICC characterisation of the press condition —
          SWOP, GRACoL or FOGRA — and this site has neither. So we publish the arithmetic we can stand
          behind and say plainly that it is a screening tool for deciding which colours deserve a proof,
          not a substitute for one.
        </Callout>
        <NoHeadroomTable />
      </Section>

      {/* ── 6. TAC chart ──────────────────────────────────────────────────── */}
      <Section id="tac-distribution" accent={ACCENT} kicker="From the dataset"
        heading="How Much Ink a Pantone Build Actually Puts on the Sheet">
        <P>
          Total area coverage decides whether a job dries, offsets or cracks at the fold, and it is the
          first number a prepress operator checks. This chart sorts every one of the{' '}
          {tacHistogram.n.toLocaleString('en-GB')} coated PMS builds into coverage bands.
        </P>
        <ChartFigure
          caption={`Total area coverage (C + M + Y + K) for all ${tacHistogram.n.toLocaleString('en-GB')} coated Pantone builds. Computed from data/pantone.json by scripts/build-color-stats.mjs.`}
          takeaway={
            <>
              <P>
                <strong>The takeaway: a single Pantone build is never the thing that breaks your ink
                limit.</strong> The median build is {tacHistogram.median}% and the mean is{' '}
                {tacHistogram.mean}%. Only {tacHistogram.buckets[4].count} builds —{' '}
                {tacHistogram.buckets[4].pct}% of the deck — exceed 200%, and the heaviest in the whole
                coated library, {tacHistogram.heaviest[0].code}, reaches {tacHistogram.max}%. Nothing here
                comes close to the ~300% limit of commercial sheetfed work.
              </P>
              <P>
                What breaks the limit is stacking. Drop a {tacHistogram.max}% build on top of a 240% rich
                black, or knock one colour out of another with a trap, and the total on that spot is what
                the press has to dry. The number to watch is not the swatch in your palette — it is the
                heaviest square millimetre of the finished artwork, which is what a preflight ink-coverage
                check reports.
              </P>
            </>
          }
        >
          <DistributionChart
            id="tac-histogram"
            title="Total ink coverage across the coated Pantone deck"
            desc={`Horizontal bar chart of ${tacHistogram.n} coated Pantone process builds grouped by total area coverage. Under 50 percent: ${tacHistogram.buckets[0].count}. 50 to 100: ${tacHistogram.buckets[1].count}. 100 to 150: ${tacHistogram.buckets[2].count}, the largest group. 150 to 200: ${tacHistogram.buckets[3].count}. 200 to 250: ${tacHistogram.buckets[4].count}. 250 and over: ${tacHistogram.buckets[5].count}.`}
            buckets={tacHistogram.buckets}
            unitLabel="PMS builds"
            barColor="#fb923c"
            highlightColor="#ea580c"
          />
        </ChartFigure>
      </Section>

      {/* ── 7. Ink build chart ────────────────────────────────────────────── */}
      <Section id="ink-build" accent={ACCENT} kicker="From the dataset"
        heading="Ink Build Comparison — Eight Colours Side by Side">
        <P>
          Two builds can carry the same total coverage and behave completely differently on press,
          because what matters is which inks are doing the work. These eight bars show the composition
          rather than the total.
        </P>
        <ChartFigure
          caption="Cyan, magenta, yellow and black percentages for eight well-known Pantone colours, stacked to a shared 250% scale, with total area coverage printed at the end of each bar."
          takeaway={
            <>
              <P>
                <strong>The takeaway: the heavy builds are heavy because of black, not because of
                colour.</strong> Pantone Yellow C is a {C['PMS Yellow C'].tac}% build made almost
                entirely of one ink — clean, cheap and easy to hold on press. Pantone Reflex Blue C runs
                to {C['PMS Reflex Blue C'].tac}% with cyan at 100%, magenta at{' '}
                {C['PMS Reflex Blue C'].cmyk.m}% and black at {C['PMS Reflex Blue C'].cmyk.k}%. That black
                is not adding depth, it is compensating: the chromatic inks have run out and the recipe is
                darkening the colour to get it close.
              </P>
              <P>
                Compare Pantone 186 C at {C['PMS 186 C'].tac}% and Pantone 485 C at {C['PMS 485 C'].tac}% —
                two similar reds with different balances. 186 leans on magenta ({C['PMS 186 C'].cmyk.m}%
                against {C['PMS 485 C'].cmyk.m}%), 485 on yellow, which is exactly why 186 reads as the
                cooler, more crimson red and 485 as the warmer, more orange one. And Pantone Black C is
                only {C['PMS Black C'].tac}%: a warm black built from {C['PMS Black C'].cmyk.k}% K plus a
                little magenta and yellow, which is why it never matches a flat 100% K.
              </P>
            </>
          }
        >
          <InkBuildChart
            id="ink-build-chart"
            title="Four-colour ink composition of eight Pantone colours"
            desc={inkBuild
              .map((c) => `${c.code}: cyan ${c.cmyk.c}, magenta ${c.cmyk.m}, yellow ${c.cmyk.y}, black ${c.cmyk.k}, total ${c.tac} percent.`)
              .join(' ')}
            colors={inkBuild}
          />
        </ChartFigure>
      </Section>

      {/* ── 8. Rich black ─────────────────────────────────────────────────── */}
      <Section id="rich-black" accent={ACCENT} kicker="Press reality"
        heading="Rich Black, Total Ink Limit and Press Reality">
        <P>
          A solid area of 100% K alone looks disappointing — washed out, slightly mottled, obviously
          thinner than the black you had in mind. The fix is a rich black: 100% K with one or more
          chromatic inks printed underneath to deepen it. A common commercial recipe is 60C 40M 40Y 100K,
          which totals 240% coverage. A cooler variant drops the yellow; a warmer one leads with magenta.
        </P>
        <P>
          The constraint is the total ink limit, the maximum coverage the press and stock will carry
          before the sheet stops behaving. Roughly: commercial sheetfed offset on coated stock sits
          around 300%, heatset web around 300%, uncoated work lower still, and coldset newsprint as low
          as 240%. Exceed it and you get set-off — wet ink transferring onto the back of the next sheet —
          along with slow drying, cracking at the fold and plugged shadows where detail should be.
        </P>
        <P>
          Those limits are baked into the standard profiles rather than being universal truths. U.S. Web
          Coated (SWOP) v2 targets American web offset. GRACoL 2006 and its successors target American
          sheetfed on premium coated stock, with a heavier ink limit and a different grey balance.
          Coated FOGRA39 and FOGRA51 target the European ISO 12647-2 condition, FOGRA51 assuming paper
          with optical brighteners. The same Pantone number converted against each of those produces a
          different build. This is why the useful question to a printer is never “what is the CMYK”, it
          is “which profile should I convert against”.
        </P>
        <H3>Two rules that prevent most reprints</H3>
        <Bullets
          items={[
            <>
              <strong>Never set small text in rich black.</strong> Four plates cannot stay in perfect
              register at speed, and 9pt type built from four inks arrives fringed with cyan or magenta.
              Body copy is 100% K, always. Save the rich black for areas large enough that a fraction of
              a millimetre of misregistration is invisible.
            </>,
            <>
              <strong>Check the artwork, not the swatch.</strong> Individual Pantone builds are modest —
              the heaviest in the coated deck is {tacHistogram.max}% — but they stack. Run an ink-coverage
              preflight on the finished file and look at the worst spot, which is usually where a heavy
              colour overlaps a rich-black panel.
            </>,
          ]}
        />
        <P style={{ margin: 0 }}>
          And on Process Black specifically: the K ink on a four-colour press is Process Black, so
          specifying it means 100% K by definition. Pantone Black C is a different ink entirely — a warm
          spot black whose build, {build('PMS Black C')}, carries magenta and yellow precisely because it
          is not the process ink. The two are not interchangeable, and{' '}
          <A href="/pantone-black/">the Pantone black comparison page</A> shows all seven deck blacks
          together.
        </P>
      </Section>

      {/* ── 9. How-to ─────────────────────────────────────────────────────── */}
      <Section id="how-to-convert" accent={ACCENT} kicker="Step by step"
        heading="How to Convert Pantone to CMYK in Illustrator and InDesign">
        <P>
          The converter above gives you the numbers. Inside a real document you usually want the
          application to do the conversion, so that every object using the colour changes together and
          nothing is left behind on a stray spot plate.
        </P>
        {HOW_TO.map((section) => (
          <div key={section.id}>
            <H3 id={section.id}>{section.heading}</H3>
            <P>{section.intro}</P>
            <Steps items={section.steps} />
          </div>
        ))}
        <Callout tone="info" title="Always finish in Separations Preview">
          Whichever route you take, the last check is the same: open Separations Preview and confirm the
          plate list shows only Cyan, Magenta, Yellow and Black. A single forgotten spot colour inside a
          placed logo is the most common cause of an unexpected fifth-plate charge, and it is invisible
          in the layout view.
        </Callout>
      </Section>

      {/* ── 10. Spot vs process ───────────────────────────────────────────── */}
      <Section id="spot-vs-process" accent={ACCENT} kicker="Decision"
        heading="Spot vs Process — When to Pay for the Extra Plate">
        <P>
          A fifth plate costs money: an extra plate, an extra unit on the press or an extra pass, extra
          make-ready, extra wash-up. Whether it is worth it is a real decision with a real answer, and
          it is not “always use spot for brand colours”.
        </P>
        <H3>Pay for the plate when</H3>
        <Bullets
          items={[
            'The colour covers a large area — a cover, a bag, a pack face. A process build that is slightly off is obvious across a big flat, and invisible in a small logo.',
            'The colour is the brand and customers recognise it from across a shop. Some reds and some blues are load-bearing in a way that a 6% hue shift genuinely damages.',
            'Our chart flags the build as having no ink headroom. Those are the colours a press operator cannot chase, so a proof that comes back short cannot be corrected on the day.',
            'The job is short-run and simple — a two-colour letterhead runs cheaper as two spot plates than as four process plates, not more expensive.',
            'The substrate is unusual. Uncoated, kraft and coloured stock all pull process builds around far more than they pull a solid spot ink.',
          ]}
        />
        <H3>Take the process build when</H3>
        <Bullets
          items={[
            'The artwork already needs full-colour photography. The four plates are on the press regardless, so the brand colour rides along free.',
            'The colour appears small — a footer logo, a spine, an icon. Nobody compares a stamp-sized mark against a swatch book.',
            'The colour is comfortably inside process reach. Most mid-tone corporate blues, greens and neutrals convert with a shift nobody notices.',
            'The run is digital. Most digital presses are CMYK-only and cannot take a spot plate at all, though some offer extended gamut with orange, green and violet units.',
          ]}
        />
        <P style={{ margin: 0 }}>
          The middle route worth knowing about is extended-gamut printing — CMYK plus orange, green and
          violet, run as a fixed seven-colour set. It reaches a large share of the Pantone library
          without a job-specific spot plate, which makes it attractive for packaging runs carrying many
          brands at once. Ask your printer whether they run it before you assume the choice is binary.
        </P>
      </Section>

      {/* ── 11. FAQ ───────────────────────────────────────────────────────── */}
      <div className="card" style={{ borderTop: `3px solid ${ACCENT}` }}>
        <FAQSection suppressSchema items={FAQ} id="faq" />
      </div>

      {/* ── 12. Related ───────────────────────────────────────────────────── */}
      <RelatedLinks
        id="related"
        accent={ACCENT}
        heading="Next Steps for a Print Job"
        intro="Picked for what someone converting a spot colour to process usually needs next, rather than a list of every tool on the site."
        links={[
          { href: '/cmyk-to-pantone/', label: 'CMYK to Pantone', why: 'The reverse: enter a process build and find the closest spot ink, for when a supplied file has no PMS number.' },
          { href: '/pantone-to-trumatch/', label: 'Pantone to Trumatch', why: 'Trumatch is a four-colour process deck, so its swatches are printable by definition — a useful sanity check on a build.' },
          { href: '/pantone-to-hks/', label: 'Pantone to HKS', why: 'The German spot-ink system, for work printed in Germany, Austria or Switzerland.' },
          { href: '/pantone-textile-to-cmyk/', label: 'Pantone Textile to CMYK', why: 'Starting builds for sublimation and direct-to-garment, where the TCX library applies rather than PMS.' },
          { href: '/pantone-to-hex/', label: 'Pantone to HEX', why: 'The screen-side value for the same colour, with coated and uncoated compared.' },
          { href: '/learn/what-is-cmyk/', label: 'What is CMYK?', why: 'How the four-colour process works, halftone screens and all, if any of the above needs grounding.' },
          { href: '/learn/coated-vs-uncoated/', label: 'Coated vs uncoated stock', why: 'Why paper changes the ink, and what that means for the build you supply.' },
          { href: '/compare/', label: 'Compare two colours', why: 'Put a spot colour and a process build side by side and get the ΔE2000 between them.' },
        ]}
      />

      {/* ── 13. Methodology ───────────────────────────────────────────────── */}
      <Section id="methodology" accent={ACCENT} kicker="Methodology"
        heading="Where These Numbers Come From — and What They Are Not">
        <P>
          Every percentage on this page is read from this site’s Pantone dataset, which holds{' '}
          {counts.total.toLocaleString('en-GB')} colours across the coated, uncoated, metallic,
          pastel-and-neon, Colour of the Year and skin-tone libraries. Derived figures — total area
          coverage, the ink-headroom counts, the two charts — are computed at build time by{' '}
          <code style={mono}>scripts/build-color-stats.mjs</code> and written to a JSON file this page
          imports, so anyone can re-run the script and get the same numbers. No value is entered by hand
          and no row appears for a colour the dataset does not contain.
        </P>
        <P>
          Colour differences quoted anywhere on this page use <strong>CIEDE2000</strong> as formulated by
          Sharma, Wu and Dalal (2005) with kL = kC = kH = 1, on Lab values converted from sRGB through
          CIE XYZ under the D65 illuminant and the 2° standard observer. Total area coverage is simply
          C + M + Y + K. Ink headroom is the count of cyan, magenta and yellow at 95% or above.
        </P>
        <Callout tone="warn" title="The limitation, stated plainly">
          The CMYK builds in this dataset are computed from each colour’s published sRGB value by the
          standard non-colour-managed formula. They are not spectrophotometer readings of printed ink,
          and they are not the output of an ICC conversion against a named press condition. That is why
          this page ranks difficult colours by ink headroom rather than publishing a press ΔE it cannot
          substantiate — a real gamut figure needs measured Lab for the spot ink and a characterisation
          of the press, and neither is in this dataset. Use these builds as a starting point to proof and
          correct, and ask your printer which profile to convert against for the actual job.
        </Callout>
        <P style={{ margin: 0, fontSize: '0.82rem', color: '#6b7280' }}>
          Ink builds and coverage figures on this page were last recomputed from the dataset on{' '}
          <time dateTime={MODIFIED}>{MODIFIED}</time>; this converter has been online since{' '}
          <time dateTime={PUBLISHED}>{PUBLISHED}</time>.
        </P>
      </Section>
    </PantoneToXPage>
  );
}
